"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { Splash } from '@/components/splash'
import { FC, ReactNode, useEffect, useState } from 'react'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })


// export const metadata: Metadata = {
//   manifest: '/manifest.json',
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

type RootLayoutProps = {
  children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children}) => {

  const pathname = usePathname()
  const isHome = pathname === '/'
  const [loading, setLoading ] = useState(isHome)

  useEffect(() => {

    if(loading){
      return
    }

  },[loading])

  return (
    <html lang="en">
      <body className={inter.className}>
        
        {
          loading && isHome ? (<Splash finishLoading={() => setLoading(false)} />)  : (<>
          {children}
          </>) 
        }
        </body>
    </html>
  )
}

export default RootLayout
